apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-deployment
  labels:
    app: gin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gin
  template:
    metadata:
      labels:
        app: gin
    spec:
      containers:
        - name: gin
          image: registry.cn-hangzhou.aliyuncs.com/ahub/example-gin:v1.0
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: gin-service
spec:
  selector:
    app: gin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080